### ISSUE TITLE
Question about experiements

### ISSUE THREAD

**Issue by HannahHaensen** [NVlabs/CenterPose#5]
Great work and nice documented repository. 

First is there a plan to update DCNv2 to the latest working then also on the newest PyTorch version?

Second, I have been wondering if there is any subsequent work planed using the NOCS dataset?

**Comment by Uio96** [comment]
Thanks for the interest.

>First is there a plan to update DCNv2 to the latest working then also on the newest PyTorch version?

Currently, we are working on some other projects. So there is no plan to upgrade it for now.

> Second, I have been wondering if there is any subsequent work planed using the NOCS dataset?

I have not tried CenterPose on the NOCS dataset yet. It may not work very well since the training data of Objectron is different from NOCS. Objectron is more object-centric while NOCS is not. It is an interesting direction to explore.
